FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o smtpsender ./cmd/smtpsender

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /app/smtpsender .

ENV SMTP_SERVER=127.0.0.1
ENV SMTP_PORT=1025
ENV INTERVAL=20s
ENV SMTP_FROM=test-sender@example.com
ENV SMTP_TO=recipient@example.com

ENTRYPOINT ["./smtpsender"]
