passdb ldap {
  ldap_uris = ldap://ldap:389
  ldap_base = ou=users,dc=example,dc=org
  ldap_auth_dn = cn=admin,dc=example,dc=org
  ldap_auth_dn_password = admin
  passdb_ldap_bind = yes
  passdb_ldap_filter = (|(uid=%u)(mail=%u))
}

userdb ldap {
  ldap_uris = ldap://ldap:389
  ldap_base = ou=users,dc=example,dc=org
  ldap_auth_dn = cn=admin,dc=example,dc=org
  ldap_auth_dn_password = admin
  userdb_ldap_filter = (|(uid=%u)(mail=%u))
}
