// Code generated from jmap-mail.json. DO NOT EDIT DIRECTLY.
package spec

var JMAPMailRequirements = []Requirement{
	{
		Spec:    "RFC2045",
		Section: "5",
		Level:   Level("MUST"),
		Text:    "MIME multipart messages are parsed into a nested body-part structure.",
		Tests:   []string{"TestEmailParse_MIMETorture", "TestRFC2045_MIMEPartStructure"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5322",
		Section: "3.6",
		Level:   Level("MUST"),
		Text:    "RFC 5322 messages are parsed into JMAP Email header/address/subject/date fields.",
		Tests:   []string{"TestEmailParse_MIMETorture", "TestRFC5322_MessageParsing"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8620",
		Section: "5.4",
		Level:   Level("MUST"),
		Text:    "Email/copy recreates emails in the target account.",
		Tests:   []string{"TestRFC8621_Section4_6_EmailCopyRoundTrip", "TestRFC8621_Section4_EmailCopy"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8620",
		Section: "5.4",
		Level:   Level("MUST"),
		Text:    "Mailbox/copy recreates mailboxes in the target account.",
		Tests:   []string{"TestRFC8621_MailboxCopy", "TestRFC8621_Section2_MailboxCopy"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8620",
		Section: "8.2",
		Level:   Level("MUST"),
		Text:    "Credential authentication must fail closed: when no credential backend is configured, a plain username == password match MUST NOT be accepted.",
		Tests:   []string{"TestRFC8620_Auth_OIDCRejectsCredentialsWithoutFallback"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "2.1",
		Level:   Level("MUST"),
		Text:    "Mailbox/get returns Mailbox objects with rights and counts.",
		Tests:   []string{"TestRFC8621_Section2_1_MailboxGet"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "2.1",
		Level:   Level("MAY"),
		Text:    "Optional system mailbox roles are supported.",
		Tests:   []string{"TestRFC8621_Section2_1_MayProvisions_OptionalSystemRoles"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "2.3",
		Level:   Level("MUST"),
		Text:    "Mailbox/set create/update/destroy, including notUpdated notFound for a missing id.",
		Tests:   []string{"TestRFC8621_MailboxSetUpdateMissingNotFound", "TestRFC8621_Section2_3_MailboxSet", "TestRFC8621_Section2_5_MailboxUpdate"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "2.4",
		Level:   Level("MUST"),
		Text:    "Mailbox/query filter conditions and sort, positive and negative.",
		Tests:   []string{"TestMailboxQuery_HasAnyRole_IsSubscribed", "TestRFC8621_Section2_4_MailboxFilterPropertiesPosNeg", "TestRFC8621_Section2_4_MailboxQuery"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "3.1",
		Level:   Level("MUST"),
		Text:    "Thread/get groups related emails; threadIds filter returns all emails of a thread.",
		Tests:   []string{"TestRFC8621_Section3_1_ThreadGet", "TestRFC8621_Section3_ThreadGet"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.1",
		Level:   Level("MUST"),
		Text:    "Email/get returns parsed properties and reconstructed body structure.",
		Tests:   []string{"TestRFC8621_EmailCreateImplicitBodyPartType", "TestRFC8621_EmailCreateReconstructsBodyStructure", "TestRFC8621_Section4_1_EmailGet"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.3",
		Level:   Level("MUST"),
		Text:    "Email/set create/update applies partial patches (incl. keywords/*) without dropping unaddressed properties.",
		Tests:   []string{"TestRFC8621_EmailSetEmptyFieldsNull", "TestRFC8621_EmailSetErrorPaths", "TestRFC8621_Section4_3_EmailSet", "TestRFC8621_Section4_3_EmailSetUpdateKeywords", "TestRFC8621_Section4_4_EmailSetPartialUpdateDataLossPrevention"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.4",
		Level:   Level("MUST"),
		Text:    "Email/query filter conditions, positive and negative.",
		Tests:   []string{"TestRFC8621_EmailQueryAllFilterConditions", "TestRFC8621_EmailQueryFilters_PositiveAndNegative", "TestRFC8621_Section4_5_1_EmailQueryFromToFilters", "TestRFC8621_Section4_5_EmailFilterPropertiesPosNeg", "TestRFC8621_Section4_5_EmailQuery"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.4.1",
		Level:   Level("MUST"),
		Text:    "Email/query text/subject/body/from are free-text searches; a client prefix-wildcard term matches a word.",
		Tests:   []string{"TestRFC8621_EmailQueryTextSearchWildcard"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.4.2",
		Level:   Level("MUST"),
		Text:    "Email/query sort comparators, including base-subject and multi-comparator tie-breaks.",
		Tests:   []string{"TestRFC8621_Section4_4_2_EmailSortBaseSubject", "TestRFC8621_Section4_4_2_EmailSortComparators", "TestRFC8621_Section4_4_2_EmailSortMultiComparator", "TestRFC8621_Section4_4_SortOrderAndMultiComparatorTieBreak"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.7",
		Level:   Level("MUST"),
		Text:    "Email/import imports RFC 5322 blobs; error paths are handled.",
		Tests:   []string{"TestRFC8621_Section4_7_EmailImport", "TestRFC8621_Section4_8_EmailImportAndParseErrorPaths", "TestRFC8621_Section4_EmailImportAndParse"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "4.8",
		Level:   Level("MUST"),
		Text:    "Email/parse parses blobs into Email objects; error paths are handled.",
		Tests:   []string{"TestEmailParse_AdversarialEdgeCases", "TestEmailParse_MIMETorture", "TestRFC8621_Section4_8_EmailParse"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "5",
		Level:   Level("MUST"),
		Text:    "SearchSnippet/get returns subject/preview snippets with <mark> highlighting.",
		Tests:   []string{"TestRFC8621_EmailCopy_SearchSnippet_Sieve_CalendarEvent", "TestRFC8621_Section5_SearchSnippetGet"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "6.1",
		Level:   Level("MUST"),
		Text:    "The default Identity email is the account's real address (used as From), not the opaque account id.",
		Tests:   []string{"TestRFC8621_IdentityEmailIsRealAddress"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "6.3",
		Level:   Level("MUST"),
		Text:    "Identity/get and Identity/set (incl. notUpdated notFound for a missing id).",
		Tests:   []string{"TestRFC8621_IdentitySetUpdateMissingNotFound", "TestRFC8621_Section6_1_IdentityGet", "TestRFC8621_Section6_IdentitySet"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "7.1",
		Level:   Level("MUST"),
		Text:    "EmailSubmission/get and /query with envelope and delivery status.",
		Tests:   []string{"TestEmailSubmission_Envelope_RoundTrip", "TestRFC8621_Section7_1_EmailSubmissionGet", "TestRFC8621_Section7_2_EmailSubmissionQuery", "TestRFC8621_SubmissionQueryAnchor", "TestRFC8621_SubmissionQueryChanges", "TestRFC8621_SubmissionQueryFilters", "TestRFC8621_SubmissionQueryPagination", "TestRFC8621_SubmissionQuery_FilterOperator", "TestRFC8621_SubmissionQuery_SortUndoStatus"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "7.5",
		Level:   Level("MUST"),
		Text:    "EmailSubmission/set sends, and applies onSuccessUpdateEmail / onSuccessDestroyEmail.",
		Tests:   []string{"TestEmailSubmissionSetDestroyTests", "TestEmailSubmission_BlobUploadImportSubmissionPipeline", "TestEmailSubmission_CreationReferences", "TestEmailSubmission_IfInStateMismatch", "TestEmailSubmission_ImmutablePropertiesNotUpdated", "TestEmailSubmission_ImportCreationReferences", "TestEmailSubmission_LocalDelivery", "TestEmailSubmission_OnSuccessDestroyEmail", "TestEmailSubmission_OnSuccessUpdateEmail", "TestEmailSubmission_OutboundSenderRelay", "TestEmailSubmission_PushStateChange", "TestEmailSubmission_UndoStatusCancelFinalCannotCancel", "TestEmailSubmission_UndoStatusCancelPending", "TestEmailSubmission_ValidationErrors", "TestRFC8621_Section7_3_EmailSubmissionSet"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8621",
		Section: "8",
		Level:   Level("MUST"),
		Text:    "VacationResponse capability, singleton get/set, and singleton create/destroy rejection.",
		Tests:   []string{"TestRFC8621_VacationResponseCapability", "TestRFC8621_VacationResponseGetSet", "TestRFC8621_VacationResponseIfInState"},
		Status:  Covered,
	},
	{
		Spec:    "RFC9007",
		Section: "2",
		Level:   Level("MUST"),
		Text:    "The MDN capability is advertised.",
		Tests:   []string{"TestRFC9007_SessionCapability"},
		Status:  Covered,
	},
	{
		Spec:    "RFC9007",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "MDN/send generates a Message Disposition Notification.",
		Tests:   []string{"TestRFC9007_MDNSend"},
		Status:  Covered,
	},
	{
		Spec:    "RFC9007",
		Section: "4",
		Level:   Level("MUST"),
		Text:    "MDN/parse parses an MDN blob.",
		Tests:   []string{"TestRFC9007_MDNParse", "TestRFC9007_MDNParse_FullConformance"},
		Status:  Covered,
	},
	{
		Spec:    "RFC9219",
		Section: "2",
		Level:   Level("MUST"),
		Text:    "The S/MIME verification capability is advertised.",
		Tests:   []string{"TestRFC9219_Section2_Capability"},
		Status:  Covered,
	},
	{
		Spec:    "RFC9219",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "Email exposes S/MIME status properties.",
		Tests:   []string{"TestRFC9219_Section3_EmailSMIMEProperties"},
		Status:  Covered,
	},
	{
		Spec:    "RFC9219",
		Section: "4",
		Level:   Level("MUST"),
		Text:    "Email/verifySmime verifies S/MIME signatures.",
		Tests:   []string{"TestRFC9219_Section4_EmailVerifySmime", "TestRFC9219_VerifySmimePayloadStructure"},
		Status:  Covered,
	},
}
