// Code generated from jmap-calendars.json. DO NOT EDIT DIRECTLY.
package spec

var JMAPCalendarsRequirements = []Requirement{
	{
		Spec:    "RFC5545",
		Section: "3.3.11",
		Level:   Level("MUST"),
		Text:    "TEXT values escape backslash, comma, semicolon and newline on write and unescape on read.",
		Tests:   []string{"TestRFC5545_TextEscapingRoundTrip"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5545",
		Section: "3.6.1",
		Level:   Level("MUST"),
		Text:    "VEVENT properties (recurrence, participants, alarms, location, timezone, duration) round-trip losslessly to and from JSCalendar.",
		Tests:   []string{"TestRFC5546_ITIPRoundTripFullFidelity"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5546",
		Section: "2.1.5",
		Level:   Level("MUST"),
		Text:    "iTIP messages use the event's uid (with SEQUENCE) as the cross-system correlation key, not the server-assigned JMAP id.",
		Tests:   []string{"TestRFC5546_ITIPUsesEventUIDAndSequence"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5546",
		Section: "3.2.2",
		Level:   Level("MUST"),
		Text:    "A REQUEST invitation carries the event's UID, SEQUENCE, ORGANIZER, and ATTENDEE lines.",
		Tests:   []string{"TestRFC5546_BuildRequestAndCancel", "TestRFC5546_ITIPRoundTripFullFidelity", "TestRFC5546_ITIPUsesEventUIDAndSequence", "TestRFC8984_SchedulingRequestExcludesOwner"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5546",
		Section: "3.2.3",
		Level:   Level("MUST"),
		Text:    "A REPLY carries the ORGANIZER being answered and the replying ATTENDEE with its PARTSTAT.",
		Tests:   []string{"TestRFC5546_BuildAndParseReply", "TestRFC5546_ITIPUsesEventUIDAndSequence", "TestRFC8984_SchedulingReplyOnRSVP"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5546",
		Section: "3.2.5",
		Level:   Level("MUST"),
		Text:    "A CANCEL carries STATUS:CANCELLED with the event's UID and SEQUENCE.",
		Tests:   []string{"TestRFC5546_BuildRequestAndCancel", "TestRFC6047_AutoSendInvitationAndCancellation"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.4",
		Level:   Level("MUST"),
		Text:    "The iMIP body part is text/calendar with a method parameter matching the iCalendar METHOD.",
		Tests:   []string{"TestRFC6047_AutoSendInvitationAndCancellation", "TestRFC8984_SchedulingRequestExcludesOwner"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8620",
		Section: "5.3",
		Level:   Level("MUST"),
		Text:    "A */set update response value is null unless the server changed properties beyond those the client sent.",
		Tests:   []string{"TestRFC8984_ParticipantIdentityLifecycle"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8620",
		Section: "5.4",
		Level:   Level("MUST"),
		Text:    "Foo/copy reads sources from fromAccountId and supports onSuccessDestroyOriginal / destroyFromIfInState.",
		Tests:   []string{"TestRFC8984_CalendarEventCopyDestroyOriginal", "TestRFC8984_CalendarEventCopyRoundTrip"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8620",
		Section: "5.5",
		Level:   Level("MUST"),
		Text:    "FilterOperator AND/OR/NOT is evaluated over nested conditions.",
		Tests:   []string{"TestRFC8984_QueryFilterOperator"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "1.4.5",
		Level:   Level("MUST"),
		Text:    "LocalDateTime (floating, no time zone) is accepted for date-time values.",
		Tests:   []string{"TestRFC8984_QueryFloatingLocalDateTimeBounds"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "4.1.2",
		Level:   Level("MUST"),
		Text:    "uid is required and stable; the server auto-generates one when absent.",
		Tests:   []string{"TestRFC8984_UIDAutoGenerateAndPersistence"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "4.3.3",
		Level:   Level("MUST"),
		Text:    "recurrenceRules expand honouring byDay.",
		Tests:   []string{"TestRFC8984_RecurrenceByDay"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "4.3.3.1",
		Level:   Level("MUST"),
		Text:    "bySetPosition is applied during recurrence expansion.",
		Tests:   []string{"TestRFC8984_RecurrenceBySetPosition"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "4.3.4",
		Level:   Level("MUST"),
		Text:    "excludedRecurrenceRules subtract instances from the expansion.",
		Tests:   []string{"TestRFC8984_ExcludedRecurrenceRules"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "4.3.5",
		Level:   Level("MUST"),
		Text:    "recurrenceOverrides apply to instances; excluded:true removes an instance.",
		Tests:   []string{"TestRFC8984_RecurrenceOverrideExcluded"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "4.4.2",
		Level:   Level("MUST"),
		Text:    "Event status is limited to confirmed/tentative/cancelled.",
		Tests:   []string{"TestRFC8984_EventStatusEnum"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8984",
		Section: "5.2.5",
		Level:   Level("MUST"),
		Text:    "Task progress is limited to needs-action/in-process/completed/failed/pending/cancelled.",
		Tests:   []string{"TestRFC8984_TaskProgressEnum"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "3.3",
		Level:   Level("MUST"),
		Text:    "ParticipantIdentity isDefault is server-set; changed only via onSuccessSetIsDefault.",
		Tests:   []string{"TestRFC8984_ParticipantIdentityLifecycle"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "4.2.7",
		Level:   Level("MUST"),
		Text:    "The scheduleStatus property represents the status of scheduling message delivery as a STATCODE string.",
		Tests:   []string{"TestRFC8984_SEC7_ScheduleStatusReporting"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "4.2.10",
		Level:   Level("MUST"),
		Text:    "privacy=private: only non-owner sharees get the reduced property set; the owner sees full data.",
		Tests:   []string{"TestRFC8984_PrivacyOwnerSeesFullData"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "4.2.10",
		Level:   Level("MUST"),
		Text:    "privacy=secret: the server behaves as though the event does not exist for users other than the owner; the owner still sees it.",
		Tests:   []string{"TestRFC8984_PrivacyOwnerSeesFullData"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "4.4",
		Level:   Level("MUST"),
		Text:    "utcStart/utcEnd computed read-only CalendarEvent properties are returned when requested.",
		Tests:   []string{"TestRFC8984_UTCStartAndUTCEndComputedProperties"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "4.4.5",
		Level:   Level("MAY"),
		Text:    "hideAttendees limits participant visibility to owners; it round-trips through set/get.",
		Tests:   []string{"TestRFC8984_HideAttendeesRoundTrip"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9",
		Level:   Level("MUST"),
		Text:    "sendSchedulingMessages (default false): when true the server sends iTIP scheduling messages after a successful create/update/destroy.",
		Tests:   []string{"TestRFC6047_AutoSendInvitationAndCancellation"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9",
		Level:   Level("MUST"),
		Text:    "noSupportedScheduleMethods is returned when scheduling is requested but no schedule method is available.",
		Tests:   []string{"TestRFC8984_SchedulingNoSupportedScheduleMethods"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9.2.1",
		Level:   Level("MUST"),
		Text:    "On create/update the origin sends a REQUEST to every current participant except the calendar owner.",
		Tests:   []string{"TestRFC8984_SchedulingRequestExcludesOwner"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9.2.1",
		Level:   Level("MUST"),
		Text:    "With hideAttendees, each REQUEST contains only its recipient (plus the owner); other attendees are omitted.",
		Tests:   []string{"TestRFC8984_SchedulingHideAttendees"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9.2.1",
		Level:   Level("MUST"),
		Text:    "A REQUEST to a local participant delivers the event into that participant's own calendar with participation still pending.",
		Tests:   []string{"TestRFC8984_SameServerInviteAcceptRoundTrip"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9.2.2",
		Level:   Level("MUST"),
		Text:    "On destroy the origin sends a CANCEL to every participant except the calendar owner.",
		Tests:   []string{"TestRFC6047_AutoSendInvitationAndCancellation"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9.2.3",
		Level:   Level("MUST"),
		Text:    "When not the origin, a REPLY is sent to the organizer when a user participant's participationStatus changes to a value other than needs-action.",
		Tests:   []string{"TestRFC8984_SchedulingReplyOnRSVP"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.9.2.3",
		Level:   Level("MUST"),
		Text:    "A REPLY from a local participant is reflected into the organizer's own copy of the event.",
		Tests:   []string{"TestRFC8984_SameServerInviteAcceptRoundTrip"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11",
		Level:   Level("MAY"),
		Text:    "expandRecurrences returns per-occurrence ids.",
		Tests:   []string{"TestRFC8984_ExpandRecurrencesQueryArg", "TestRFC8984_RecurrenceExpansionQuery"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11",
		Level:   Level("MUST"),
		Text:    "The timeZone argument (default Etc/UTC) is used to interpret before/after bounds.",
		Tests:   []string{"TestRFC8984_QueryFloatingLocalDateTimeBounds"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11",
		Level:   Level("SHOULD"),
		Text:    "canCalculateChanges is false when expandRecurrences is set (synthetic occurrence ids are not change-tracked).",
		Tests:   []string{"TestRFC8984_QueryCanCalculateChanges"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11",
		Level:   Level("SHOULD"),
		Text:    "minDateTime/maxDateTime/maxExpandedQueryDuration capability limits are enforced on queries.",
		Tests:   []string{"TestRFC8984_CalendarQueryCapabilityLimits"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.1",
		Level:   Level("MAY"),
		Text:    "inCalendars matches events in any listed calendar.",
		Tests:   []string{"TestRFC8984_InCalendarsFilter"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.1",
		Level:   Level("MUST"),
		Text:    "before/after are LocalDateTime, matched against the event's start/end in the timeZone argument.",
		Tests:   []string{"TestRFC8984_QueryFloatingLocalDateTimeBounds"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.1",
		Level:   Level("MUST"),
		Text:    "before/after accept date-only (LocalDate) values.",
		Tests:   []string{"TestRFC8984_QueryLocalDateBounds"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.1",
		Level:   Level("MUST"),
		Text:    "unknown filter conditions are rejected with unsupportedFilter (no fallthrough match).",
		Tests:   []string{"TestRFC8984_QueryRejectsUnknownFilter"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.1",
		Level:   Level("SHOULD"),
		Text:    "before/after are DST-correct in a non-UTC timeZone.",
		Tests:   []string{"TestRFC8984_QueryDSTTransitionBounds"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.2",
		Level:   Level("MUST"),
		Text:    "sort comparators are limited to supported properties; unknown -> unsupportedSort.",
		Tests:   []string{"TestRFC8984_QueryRejectsUnknownSort"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.11.2",
		Level:   Level("MUST"),
		Text:    "sort supports start, uid, and recurrenceId.",
		Tests:   []string{"TestRFC8984_CalendarEventQuerySorting"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "5.12",
		Level:   Level("MAY"),
		Text:    "CalendarEvent/parse converts iCalendar blobs to JSCalendar events.",
		Tests:   []string{"TestRFC8984_CalendarEventParse"},
		Status:  Covered,
	},
	{
		Spec:    "draft-ietf-jmap-calendars-27",
		Section: "7.2",
		Level:   Level("MUST"),
		Text:    "CalendarEventNotification objects are server-created and can be fetched, queried, and destroyed.",
		Tests:   []string{"TestRFC8984_CalendarEventNotificationLifecycle"},
		Status:  Covered,
	},
}
