// Code generated from smtp.json. DO NOT EDIT DIRECTLY.
package spec

var SMTPRequirements = []Requirement{
	{
		Spec:    "RFC4954",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "The EHLO keyword value associated with this extension is AUTH, and the AUTH EHLO keyword contains as a parameter a space-separated list of the names of available SASL mechanisms.",
		Tests:   []string{"TestRFC4954_SMTPAuthOverWire"},
		Status:  Covered,
	},
	{
		Spec:    "RFC4954",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "The AUTH extension is appropriate for the submission protocol, not for the unauthenticated inbound MX relay path.",
		Tests:   []string{"TestRFC6409_MXServerDoesNotAdvertiseAUTH"},
		Status:  Covered,
	},
	{
		Spec:    "RFC4954",
		Section: "4",
		Level:   Level("MUST"),
		Text:    "Should the client successfully complete the exchange, the SMTP server issues a 235 reply.",
		Tests:   []string{"TestRFC4954_SMTPAuthOverWire"},
		Status:  Covered,
	},
	{
		Spec:    "RFC4954",
		Section: "6",
		Level:   Level("SHOULD"),
		Text:    "530 5.7.0 Authentication required: this response SHOULD be returned by any command other than AUTH, EHLO, HELO, NOOP, RSET, or QUIT when server policy requires authentication in order to perform the requested action and authentication is not currently in force.",
		Tests:   []string{"TestRFC6409_SubmissionRequiresAuthentication", "TestRFC6409_SubmissionRequiresAuthenticationOverWire"},
		Status:  Covered,
	},
	{
		Spec:    "RFC4954",
		Section: "6",
		Level:   Level("SHOULD"),
		Text:    "535 5.7.8 Authentication credentials invalid: the authentication failed due to invalid or insufficient authentication credentials.",
		Tests:   []string{"TestRFC4954_AuthFailureOverWire", "TestRFC4954_AuthPlainInvalidCredentialsRejected"},
		Status:  Covered,
	},
	{
		Spec:    "RFC4954",
		Section: "7",
		Level:   Level("SHOULD"),
		Text:    "Upon successful authentication, a server SHOULD use the ESMTPA or the ESMTPSA (when appropriate) keyword in the with clause of the Received header field.",
		Tests:   []string{"TestRFC4954_ReceivedWithClauseESMTPA", "TestRFC6409_SubmissionDeliversMessageWithESMTPAReceived"},
		Status:  Covered,
	},
	{
		Spec:    "RFC4954",
		Section: "9",
		Level:   Level("MUST"),
		Text:    "If an implementation supports SASL mechanisms that are vulnerable to passive eavesdropping attacks (such as PLAIN), then the implementation MUST support at least one configuration where these SASL mechanisms are not advertised or used without the presence of an external security layer such as TLS.",
		Tests:   []string{"TestRFC4954_NoInsecureAuthConfigurationOverWire", "TestRFC4954_PlainMechanismOnlyWithSecureLayer"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5228",
		Section: "4.1",
		Level:   Level("MUST"),
		Text:    "The fileinto action files the message into the specified mailbox.",
		Tests:   []string{"TestRFC5228_SieveFileinto"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5228",
		Section: "4.2",
		Level:   Level("MUST"),
		Text:    "The redirect action forwards the message to another email address.",
		Tests:   []string{"TestRFC5228_SieveRedirect"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5228",
		Section: "4.3",
		Level:   Level("MUST"),
		Text:    "The discard action silently drops the message without delivery.",
		Tests:   []string{"TestRFC5228_SieveDiscard"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5232",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "The addflag and setflag actions add or replace IMAP flags and keywords on the message.",
		Tests:   []string{"TestRFC5228_SieveAddFlag"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5321",
		Section: "3.4",
		Level:   Level("MUST"),
		Text:    "A receiving SMTP server rejects recipients it cannot deliver to (relaying denied) rather than accepting the message.",
		Tests:   []string{"TestRFC5321_RejectExternalRecipient"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5321",
		Section: "3.7",
		Level:   Level("MUST"),
		Text:    "A receiving SMTP server must not reply 250 to DATA when the message could not be stored for any recipient; it must return a failure reply.",
		Tests:   []string{"TestRFC5321_DataStorageFailureReturns451", "TestSMTPReceiver_MIMETorture", "TestSMTPReceiver_OversizedMessageDATA"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5321",
		Section: "4.4",
		Level:   Level("MUST"),
		Text:    "A receiving SMTP server prepends a Received: trace header to the accepted message content.",
		Tests:   []string{"TestLocalDelivery_UserToUserOverSMTP"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5429",
		Section: "2",
		Level:   Level("MUST"),
		Text:    "The reject action terminates delivery and rejects the message with an SMTP error response.",
		Tests:   []string{"TestRFC5228_SieveReject"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5546",
		Section: "3.2.2",
		Level:   Level("MUST"),
		Text:    "An inbound REQUEST imports the full event (recurrence, duration, location, participants) into the invitee's calendar.",
		Tests:   []string{"TestRFC6047_InboundRequestFullFidelityMultipart"},
		Status:  Covered,
	},
	{
		Spec:    "RFC5546",
		Section: "3.2.3",
		Level:   Level("MUST"),
		Text:    "An inbound REPLY updates the replying attendee's participationStatus on the UID-correlated event, not the event-level status.",
		Tests:   []string{"TestRFC6047_InboundReplyUpdatesParticipationStatus"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Authentication gate: without a configured SenderVerifier (development mode) the gate is skipped.",
		Tests:   []string{"TestCheckSenderAuth_NoVerifierDevelopmentMode"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Local trust exception: loopback clients are trusted without SPF/DKIM/DMARC validation so local delivery works.",
		Tests:   []string{"TestCheckSenderAuth_LoopbackClientTrusted", "TestRFC6047_SenderAuth_LocalDeliveryWorksWithoutValidation"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Local trust exception: envelope senders that are local accounts of this server are trusted without DNS validation.",
		Tests:   []string{"TestCheckSenderAuth_LocalAccountSenderTrusted"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Unauthenticated messages may not be trusted: verification errors fail closed.",
		Tests:   []string{"TestCheckSenderAuth_VerifierErrorFailsClosed"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Authenticated sender passes the gate and the iTIP REPLY is applied.",
		Tests:   []string{"TestRFC6047_SenderAuth_DMARCOrgDomainDiscoveryApplies", "TestRFC6047_SenderAuth_SPFPassAppliesREPLY"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Unauthenticated messages may not be trusted: the message is delivered to the mailbox but never mutates calendar state.",
		Tests:   []string{"TestRFC6047_SenderAuth_DMARCPolicyRejectBlocks", "TestRFC6047_SenderAuth_SPFFailNoMutation"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Authenticated sender passes the gate and the iTIP REQUEST is imported.",
		Tests:   []string{"TestRFC6047_SenderAuth_DKIMPassImportsREQUEST"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Unauthenticated messages may not be trusted: absence of SPF, DKIM and DMARC information fails closed.",
		Tests:   []string{"TestRFC6047_SenderAuth_NoAuthInfoFailClosed", "TestVerify_FailClosedWithEmptyDNS"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Unauthenticated messages may not be trusted: DNS errors fail closed.",
		Tests:   []string{"TestRFC6047_SenderAuth_DNSTimeoutFailClosed"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Transport-boundary trust: an iTIP message submitted by an RFC 4954 authenticated client on the submission transport is applied without DNS sender authentication.",
		Tests:   []string{"TestSenderAuth_AuthenticatedSubmissionTrusted"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.2.2",
		Level:   Level("MUST"),
		Text:    "Unauthenticated messages may not be trusted: the same message on the MX transport is blocked because the sender cannot be verified.",
		Tests:   []string{"TestSenderAuth_MXBoundaryDoesNotTrustEnvelope"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.4",
		Level:   Level("MUST"),
		Text:    "A received text/calendar body with method=REPLY is processed as an iTIP scheduling response.",
		Tests:   []string{"TestRFC6047_InboundReplyUpdatesParticipationStatus"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "2.4",
		Level:   Level("MUST"),
		Text:    "The text/calendar part is located and decoded via a MIME parser (honouring Content-Transfer-Encoding), not raw byte scanning.",
		Tests:   []string{"TestRFC6047_InboundRequestFullFidelityMultipart"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6047",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "Security Considerations: the originator of an iCalendar object must be authenticated by a recipient.",
		Tests:   []string{"TestCheckSenderAuth_ExternalSenderVerified"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6376",
		Section: "6.1",
		Level:   Level("MUST"),
		Text:    "Every DKIM-Signature header field of the message is verified; a verified signature authenticates the message.",
		Tests:   []string{"TestRFC6047_SenderAuth_DKIMPassImportsREQUEST"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6409",
		Section: "3.1",
		Level:   Level("MUST"),
		Text:    "Port 587 is reserved for email message submission as specified in this document. Messages received on this port are defined to be submissions. The protocol used is ESMTP, with additional restrictions or allowances as specified here.",
		Tests:   []string{"TestRFC6409_SubmissionRequiresAuthenticationOverWire"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6409",
		Section: "4.3",
		Level:   Level("MUST"),
		Text:    "The MSA MUST, by default, issue an error response to the MAIL command if the session has not been authenticated using SMTP-AUTH, unless it has already independently established authentication or authorization (such as being within a protected subnetwork).",
		Tests:   []string{"TestRFC6409_SubmissionRequiresAuthentication", "TestRFC6409_SubmissionRequiresAuthenticationOverWire"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6409",
		Section: "6.1",
		Level:   Level("MAY"),
		Text:    "The MSA MAY issue an error response to a MAIL command if the address in MAIL FROM appears to have insufficient submission rights or is not authorized with the authentication used (if the session has been authenticated). Reply code 550 with an appropriate enhanced status code, such as 5.7.1, is used for this purpose.",
		Tests:   []string{"TestRFC6409_SubmissionSenderMustMatchAuthenticatedIdentity", "TestRFC6409_SubmissionSenderMustMatchAuthenticatedUserOverWire"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6409",
		Section: "6.2",
		Level:   Level("MAY"),
		Text:    "The MSA MAY issue an error response to a RCPT command if inconsistent with the permissions given to the user (if the session has been authenticated). Reply code 550 with an appropriate enhanced status code, such as 5.7.1, is used for this purpose.",
		Tests:   []string{"TestRFC6409_SubmissionRcptPermissions"},
		Status:  Covered,
	},
	{
		Spec:    "RFC6409",
		Section: "8.3",
		Level:   Level("SHOULD"),
		Text:    "The MSA SHOULD add or replace the Message-ID field, if it lacks it, or it is not valid syntax.",
		Tests:   []string{"TestRFC6409_SubmissionAddsMessageID", "TestRFC6409_SubmissionDeliversMessageWithESMTPAReceived"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7208",
		Section: "2.6.3",
		Level:   Level("MUST"),
		Text:    "A 'pass' result is an explicit statement that the client is authorized to inject mail with the given identity.",
		Tests:   []string{"TestRFC6047_SenderAuth_SPFPassAppliesREPLY"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7208",
		Section: "2.6.4",
		Level:   Level("MUST"),
		Text:    "A 'fail' result is an explicit statement that the client is not authorized to use the domain in the given identity.",
		Tests:   []string{"TestRFC6047_SenderAuth_SPFFailNoMutation"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7208",
		Section: "4.6.4",
		Level:   Level("MUST"),
		Text:    "Check Host() when a DNS error occurs: results other than 'domain does not exist' yield 'temperror'.",
		Tests:   []string{"TestRFC6047_SenderAuth_DNSTimeoutFailClosed"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7489",
		Section: "3.1",
		Level:   Level("MUST"),
		Text:    "Identifier Alignment: strict mode requires an exact FQDN match; relaxed mode compares Organizational Domains.",
		Tests:   []string{"TestAligned_StrictAndRelaxedModes", "TestRFC6047_SenderAuth_DMARCOrgDomainDiscoveryApplies"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7489",
		Section: "3.2",
		Level:   Level("MUST"),
		Text:    "Organizational Domain heuristic: the registered domain is the last two DNS labels.",
		Tests:   []string{"TestOrganizationalDomain_Heuristic"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7489",
		Section: "6.6.1",
		Level:   Level("MUST"),
		Text:    "Extract Author Domain: messages without a usable RFC5322.From domain are not processed.",
		Tests:   []string{"TestExtractFromDomain_FailClosedCases"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7489",
		Section: "6.6.2",
		Level:   Level("MUST"),
		Text:    "Step 5: if no Authenticated Identifier aligns with the RFC5322.From domain, the message fails the DMARC check.",
		Tests:   []string{"TestRFC6047_SenderAuth_DMARCPolicyRejectBlocks"},
		Status:  Covered,
	},
	{
		Spec:    "RFC7489",
		Section: "6.6.3",
		Level:   Level("MUST"),
		Text:    "Policy Discovery: when no record exists at the RFC5322.From domain, the DMARC record at the Organizational Domain is used.",
		Tests:   []string{"TestRFC6047_SenderAuth_DMARCOrgDomainDiscoveryApplies"},
		Status:  Covered,
	},
	{
		Spec:    "RFC8601",
		Section: "3",
		Level:   Level("MUST"),
		Text:    "Authentication-Results header indicates message authentication status.",
		Tests:   []string{"TestRFC8601_AuthenticationResultsHeader"},
		Status:  Covered,
	},
}
